name: 📙 Documentation

on: workflow_call

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Install
        uses: remileduc/vcards-io/.github/actions/package-install@main

      - name: Build documentation
        run: npm run doc
